export const NUMBER_UNSAFE = 'Numbers are unsafe, use BigInt, Long or Bytes'
export const NUMBER_NEGATIVE = 'Numbers need to be positive (>= 0)'
export const NUMBER_FLOATING_POINT = 'Number needs to be an integer'
export const UINT32_TOO_LARGE = 'Numbers need to be smaller or equal 0xffffffff'
export const INT32_TOO_LARGE = 'Numbers need to be smaller or equal 0x7fffffff'
export const INT32_TOO_SMALL = 'Numbers need to be bigger or equal -0x80000000'
export const INVALID_LONG = 'Input not coerceable to a long number'
export const INVALID_NUMBER = 'Input not coerceable to a number'
export const NAN = 'Input is NaN'
